<a href="https://colab.research.google.com/github/Kristel04/LinearAlgebra1T-2021-2022/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Algebra for CHE
## Laboratory 3: Matrix Operations

## Objectives
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve the intermediate equations.
3. Apply matrix algebra in engineering solutions 

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transporsition

One of the fundamental operations in matrix algebra is Transposition. The transport of a matrix is done by flipping tha values of its elements over its diagonals. With these, rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$.

$$A = \begin{bmatrix} 1 & 4 & 5\\7 & -9 & 11 \\ 1 & -3 & 5\end{bmatrix}$$

$$A^T = \begin{bmatrix} 1 & 7 & 1\\4 & -9 & -3 \\ 5 & 11 & 5\end{bmatrix}$$

This can now be achieved programmatically by using np.tramspose() or using the T method.

In [2]:
A = np.array([
    [1,4,5],
    [7,-9,11],
    [1,-3,5]
])
A

array([[ 1,  4,  5],
       [ 7, -9, 11],
       [ 1, -3,  5]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 1,  7,  1],
       [ 4, -9, -3],
       [ 5, 11,  5]])

In [4]:
AT2 = A.T
AT2

array([[ 1,  7,  1],
       [ 4, -9, -3],
       [ 5, 11,  5]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [1,2,3,4,5],
    [1,3,4,1,4],
])
B.shape

(2, 5)

In [7]:
np.transpose(B).shape

(5, 2)

In [8]:
B.T.shape

(5, 2)

Try to create own matrix (you can try non-squares) to test transposition.

In [9]:
Z=np.array([
    [2,4,6,8],
    [3,6,9,12]
])
Z.shape

(2, 4)

In [10]:
np.transpose(Z).shape

(4, 2)

In [11]:
Z.T.shape

(4, 2)

In [12]:
ZT = Z.T
ZT

array([[ 2,  3],
       [ 4,  6],
       [ 6,  9],
       [ 8, 12]])

## Dot Product / Inner Product

Using the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices and $Y$:

$$X = \begin{bmatrix} X(0,0) & X(0,1) \\X(1,0) & X(1,1)\end{bmatrix}$$,$$Y = \begin{bmatrix} X(0,0) & X(0,1) \\X(1,0) & X(1,1)\end{bmatrix}$$


The dot product will then be computed as:

$$X.Y = \begin{bmatrix} X(0,0) * Y(0,0) + X(0,1) * Y(1,0) & X(0,0) * Y(0,1) + X(0,1) * Y(1,1)\\ X(1,0) * Y(0,0) + X(1,1) * Y(1,0) & X(1,0) * Y(0,1) + X(1,1) * Y(1,1)\end{bmatrix}$$

So if we assign values to $X$ and $Y$:

$$X = \begin{bmatrix} -10 & -8 & -6 & -4 & -2 & 2 & 4 & 6 & 8 & 10 \\ -12 & -9 & -6 & -3 & 0 & 3 & 6 & 9 & 12\end{bmatrix}$$, 
$$Y = \begin{bmatrix} 1 & 3 & 5 & 7 & 9 \\ 2 & 4 & 6 & 8 & 10\end{bmatrix}$$

$$X.Y = \begin{bmatrix} 1 * -1 + 2 * 2 &  1 * 0 + 2 * 2\\ 0 * -1 + 1 * 2 & 0 * 0 + 1 * 2\end{bmatrix}$$ $$ \begin{bmatrix} 3 & 4 \\2 & 2\end{bmatrix}$$

This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [13]:
X = np.array([
    [-10,8],
    [-12,9]
])
Y = np.array([
    [1,3],
    [2,4]
])

In [14]:
np.array_equiv(X,Y)

False

In [15]:
np.dot(X,Y)

array([[6, 2],
       [6, 0]])

In [16]:
X.dot(Y)

array([[6, 2],
       [6, 0]])

In [17]:
X @ Y

array([[6, 2],
       [6, 0]])

In [18]:
np.matmul(X,Y)

array([[6, 2],
       [6, 0]])

In [19]:
D = np.array([
    [-2,0,3],
    [-3,1,4],
    [-4,2,4]
])
E = np.array ([
    [-4,2,4],
    [4,6,8],
    [9,6,4]
])

In [20]:
np.array_equiv(D,E)

False

In [21]:
np.dot(D,E)

array([[35, 14,  4],
       [52, 24, 12],
       [60, 28, 16]])

In [22]:
D.dot(E)

array([[35, 14,  4],
       [52, 24, 12],
       [60, 28, 16]])

In [23]:
D @ E

array([[35, 14,  4],
       [52, 24, 12],
       [60, 28, 16]])

In [24]:
np.matmul(D,E)

array([[35, 14,  4],
       [52, 24, 12],
       [60, 28, 16]])

In matix dot products there are additional rules compared with vector dot producs.

##Rule 1: The inner dimensions of the matrices in question must be the same.

Given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix} 4 & 2\\5 & -1\\ 0 & -5\end{bmatrix}$$, $$B = \begin{bmatrix} 5 & 8\\7 & -2\\ 1 & -4\end{bmatrix}$$, $$C = \begin{bmatrix} 7 & 4 & 8\\5 & -4 & 2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2), B$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A*C, or B*C.$

In [25]:
A = np.array([
    [4,2],
    [5,-1],
    [0,-5]
])
B = np.array([
    [5,8],
    [7,-2],
    [1,-4]
])
C = np.array([
    [7,4,8],
    [5,-4,2]
]) 
print(A.shape),
print(B.shape),
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [26]:
A @ C

array([[ 38,   8,  36],
       [ 30,  24,  38],
       [-25,  20, -10]])

In [27]:
B @ C

array([[ 75, -12,  56],
       [ 39,  36,  52],
       [-13,  20,   0]])

If you would notice the shape of thedot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shape of the matrices used. So recall $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c), A*B$ should have a shape $(a,c)$.

In [28]:
A @ B.T

array([[ 36,  24,  -4],
       [ 17,  37,   9],
       [-40,  10,  20]])

In [29]:
X = np.array([
    [3,4,5,6]
])
Y = np. array([
    [2,0,4,-2]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [30]:
Y.T @ X

array([[  6,   8,  10,  12],
       [  0,   0,   0,   0],
       [ 12,  16,  20,  24],
       [ -6,  -8, -10, -12]])

In [31]:
X @ Y.T

array([[14]])

You can see that when you try to multiply A and B, it returns ValueError pertaining to matrix shape mismatch.

##Rule 2: Dot Product has special properties

Dot product are prevalent in matrix algebra, this implies that it has severa; unique properties and it should be considered when formulation solutions:

1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$


I'll be doing just one  of the properties and I'll  leave the rest to test your skills!

In [32]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,1,1]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [35]:
np.array_equal(A@B, B@A)

False

In [36]:
E = A @ (B @ C)
E

array([[ 58,  27,  43],
       [107,  47,  80],
       [ 25,  12,  19]])

In [37]:
F = (A @ B) @ C
F

array([[ 58,  27,  43],
       [107,  47,  80],
       [ 25,  12,  19]])

In [38]:
np.array_equal(E,X)

False

In [39]:
np.array_equiv(E,F)

True

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
A @ E

array([[413, 187, 308],
       [792, 355, 591],
       [190,  86, 142]])

In [42]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.array_equal(a_dot_z,z_mat)

True

In [45]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Derterminant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or |$A$|. So let say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [46]:
A = np.array([
    [3,6],
    [2,5]
])
np.linalg.det(A)

3.0000000000000004

In [47]:
B = np.array([
              [3, 7, 4],
              [1, -3 ,-3],
              [0, -4, 3]
])
np.linalg.det(B)

-100.00000000000004

In [48]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [3,5,7,8],
    [0,4,2,4],
    [5,3,6,1],
    [3,1,4,7]
])
np.linalg.det(B)

-192.0

##Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [49]:
M = np.array([
    [3,9],
    [-5, 3]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 0]])

In [50]:
P = np.array([
              [4, 7, -2],
              [6, 4, -3],
              [1, 4, 8]
])
Q = np.linalg.inv(P)
Q

array([[-0.19909502,  0.28959276,  0.05882353],
       [ 0.23076923, -0.15384615,  0.        ],
       [-0.09049774,  0.04072398,  0.11764706]])

In [51]:
P @ Q

array([[ 1.00000000e+00,  2.22044605e-16, -2.77555756e-17],
       [ 2.77555756e-17,  1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  1.11022302e-16,  1.00000000e+00]])

In [52]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [14,8,27,4,0,35,15],
    [2,44,10,1,12,14,22],
    [15,19,2,10,8,0,5],
    [11,16,5,2,5,4,14],
    [18,-3,4,9,0,7,11],
    [-5,10,-2,0,-4,6,-13],
    [-2,-3,10,12,15,22,-12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [53]:
squad = np.array([
    [1.5, 1.5, 1.0],
    [2.7, 1.2, 0.4],
    [2.3, 0.5, 1.0]
])
weights = np.array([
    [0.2, 0.7, 0.7]
])
p_grade = squad @ weights.T
p_grade


array([[2.05],
       [1.66],
       [1.51]])

##Activity

## Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [54]:
np.array([])

array([], dtype=float64)

In [55]:
import numpy as np 

In [56]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>


In [57]:
print(arr.ndim)

1


In [58]:
print(arr[0])

1


In [59]:
print(arr[1:5])

[2 3 4 5]


In [60]:
for x in arr:
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [61]:
x = np.where(arr == 4)
print(x)

(array([3]),)


## Conclusion